development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: travel_hipe_development
  pool: 5
  username: th
  password: qwerty123

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: travel_hipe_test
  pool: 5
  username: th
  password: qwerty123

